### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by henrysun1996** [zkcys001/UDAStrongBaseline#10]
你好，复现实验的时候出现以下问题：
![image](https://user-images.githubusercontent.com/73630873/119468651-3bfc1200-bd79-11eb-9bc2-ebb4a2b40628.png)

请问如何解决呢？

**Comment by zkcys001** [comment]
你好，请问你是跑的哪个代码出了这个错呢?

**Comment by henrysun1996** [comment]
你好老师，运行的1. Stronger Baseline里面的第二阶段的代码，就是sh scripts/dbscan_baseline_market2duke.sh这个代码

**Comment by henrysun1996** [comment]
1. Stronger Baseline里面的第一阶段的 sh scripts/pretrain_market1501.sh 代码没有出错；
2. Uncertainty(AAAI 2021)里面的第一阶段和第二阶段的代码也都没有出错。我使用的4块GPU跑的

**Comment by zkcys001** [comment]
嗯嗯，我刚刚检查了一下sbs_traindbscan.py的代码上传成老版本的了，是有这个bug，应该是伪标签的范围越界了在计算CE LOSS时候。

我现在更新了一下代码，跑了一下是没问题的~你可以试一下，如果有性能问题或者bug的话烦请告知！

kecheng

**Comment by henrysun1996** [comment]
没问题 ，谢谢您了 目前再跑2. Uncertainty(AAAI 2021)里面的代码。结束之后，我再跑那个新的
