### ISSUE TITLE
请问可以使用单卡训练吗？大概需要多少显存？

### ISSUE THREAD

**Issue by LeeYushan** [zkcys001/UDAStrongBaseline#11]

**Comment by henrysun1996** [comment]
我试过了，所有的第二阶段的代码必须使用4块GPU跑。我用3块都跑不起来

**Comment by zkcys001** [comment]
目前第二阶段是只支持4卡的，单卡性能会降低很多

**Comment by mookixiao** [comment]
> 目前第二阶段是只支持4卡的，单卡性能会降低很多

请问第二阶段为什么只支持四卡呢？理论上超参都设为相同精度结果应该是差不多的吧？
我现在正在用单张3090 24gb训练uncertainty，正在等结果
