### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by henrysun1996** [zkcys001/UDAStrongBaseline#12]
你好，market1501数据集的gallery必须是15913张吗？我一开始跑错了那个19732的数据集，效果好像是比您这个差的。
另外一个问题就是，您代码里面的batch-size是64，是否这个是最优呢？您有尝试改大或者小会有更好的效果吗？

**Comment by zkcys001** [comment]
batch-size目前只试了64的，这个是参考fastreid里BOT的setting
