### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by yanchi2021** [zkcys001/UDAStrongBaseline#13]
![image](https://user-images.githubusercontent.com/84143871/119919703-937ac780-bf9d-11eb-9f71-1e75cc65e348.png)
第一阶段预训练代码没问题，但是第二阶段跑baseline的时候出现这个问题。我是用了两块GPU，其他的都没有变。请问是环境问题还是GPU数量的问题呢？

**Comment by zkcys001** [comment]
对的，4卡没问题。双卡会有这个bug
