### ISSUE TITLE
Strong baseline

### ISSUE THREAD

**Issue by clarkhedi** [zkcys001/UDAStrongBaseline#14]
您好，我想请问一下uncertainty论文中提到的Sbase.与代码README中所说的Our strong baseline两者是一样的吗？为什么两者性能有差别？如下图：
![lunwen_baseline](https://user-images.githubusercontent.com/47168403/120091226-be9b1d80-c13b-11eb-9b0a-781ad6548cd5.png)
![code_baseline](https://user-images.githubusercontent.com/47168403/120091232-c78bef00-c13b-11eb-9f86-a90b4a594ebf.png)

**Comment by zkcys001** [comment]
您好，在这个代码库我用了GeM Pooling代替了论文中的Global Avg Pooling

**Comment by clarkhedi** [comment]
哦哦。还有，其中两者用的对比损失都是circle loss吗？

**Comment by zkcys001** [comment]
嗯啊，只有memory bank里的loss用的是circle loss。

**Comment by clarkhedi** [comment]
嗯嗯，非常感谢你的回答。
