### ISSUE TITLE
训练到一定epoch停滞的问题

### ISSUE THREAD

**Issue by LeeYushan** [zkcys001/UDAStrongBaseline#15]
![断掉的39epoch](https://user-images.githubusercontent.com/26667261/120730310-c976f900-c513-11eb-9d2d-7480a98a6d09.PNG)
跑Stronger Baseline的时候，训到一定epoch之后就会停下来，显存不释放，也不继续往下训练，请问是什么问题啊？
一般会出现在[0/300]这个点之后

**Comment by LeeYushan** [comment]
我跑的是第二阶段的代码

**Comment by zkcys001** [comment]
我之前在集群跑的时候会遇到这个问题，那个是IO的问题，读写数据那会停滞。
在云主机和实体的机器上跑好像没遇到过这个问题

**Comment by mookixiao** [comment]
我也遇到过这个问题，没找到具体原因，建议后来者如果遇见可以换台机器试试
