### ISSUE TITLE
关于消融实验

### ISSUE THREAD

**Issue by woocoder** [zkcys001/UDAStrongBaseline#16]
你好，请问这个结果应该怎么复现呢？
<img width="704" alt="图片" src="https://user-images.githubusercontent.com/11451001/124435133-401f4480-dda7-11eb-817d-789e81a342e8.png">

我尝试了把--lambda-reg参数设置为0，但map一度只能达到5%左右，因为看到Loss_reg主要是对u_i取了均值，所以不是很明白，为什么把这一项去掉后，会导致这么大程度的精度下降，期待解答，谢谢！

**Comment by woocoder** [comment]
发现问题了，指标只是在初期上升的慢一些而已

**Comment by zkcys001** [comment]
这个版本的代码和paper版本的有点区别，可能消融实验结论会不太一样~

**Comment by woocoder** [comment]
> 这个版本的代码和paper版本的有点区别，可能消融实验结论会不太一样~

好的，多谢回复～
