### ISSUE TITLE
关于fine-tune阶段source data 的ID loss 问题

### ISSUE THREAD

**Issue by yanty123** [zkcys001/UDAStrongBaseline#18]
作者您好，
在论文中注意到在fine-tune阶段也同时用了source data 的标签计算ID LOSS， 但是我在 trainer.py 中DbscanBaseTrainer_unc_ema 这个类并没有找到 源域的分类损失，可否告知这部分是在哪里实现的呢？ 多谢！

**Comment by zkcys001** [comment]
您好，这个版本的代码改成了Source的ID loss用的是基于circle loss的contrastive loss了：https://github.com/zkcys001/UDAStrongBaseline/blob/37c55cc514bb81ccaa2798e4ad8ea72c3be7e5ef/UDAsbs/memorybank/NCEAverage.py#L281

**Comment by yanty123** [comment]
> 您好，这个版本的代码改成了Source的ID loss用的是基于circle loss的contrastive loss了：
> 
> https://github.com/zkcys001/UDAStrongBaseline/blob/37c55cc514bb81ccaa2798e4ad8ea72c3be7e5ef/UDAsbs/memorybank/NCEAverage.py#L281

明白了 谢谢！
