### ISSUE TITLE
Very bad result for cross-domain reid

### ISSUE THREAD

**Issue by shuxjweb** [zkcys001/UDAStrongBaseline#2]
I have pretrained duke and market using source_pretrain.py  and get satisfied supervised results. 
Rank1: 95.3% (market, re-ranking)
Rank1: 89.5% (duke,  re-ranking)
To test target dataset directly:
market->duke: Rank1: 56.2%
duke->market: Rank1: 65.8%
However, the result of cross-domain using sbs_traindbscan.py is very bad. 
source: duke,  target: market
using pretrained model on duke
Rank1: 46.9%, mAP:23.7
All the parameters are given from your code, the performance cannot be improved by the clustering and decay all the time while training. I don't know why?

**Comment by zkcys001** [comment]
There some bugs on Backbone, so I will fix them today.
You can try the new version of the code tomorrow~
Thx for your valuable comments. If you have any questions, please feel free to contact me. Thank you!

**Comment by zkcys001** [comment]
I have updated the fixed code. You can try the new version of the code~
best~
