### ISSUE TITLE
训练精度不对齐的问题

### ISSUE THREAD

**Issue by Youngboy12** [zkcys001/UDAStrongBaseline#20]
1、我直接使用作者的源码，把四卡换成的两卡，第一步精度就差了很多，想请问是什么原因？
设置 | mAP(%) | top-1(%) | top-5(%) | top-10(%) | mAP(%) | top-1(%) | top-5(%) | top-10(%)
pretrain_dukemtmc.sh | 74 | 86.4 | 93.4 | 95.5 | 32 | 61.5 | 76.2 | 81.1
pretrain_uncertainty_dukemtmc.sh | 73.3 | 86.2 | 93.3 | 94.9 | 29.5 | 58.4 | 73.9 | 79.3

2、Direct infer指的是Stronger Baseline预训练的精度还是Uncertainty预训练的精度？

3、第二步必须用4卡的原因的是什么？有什么办法可以使用2卡来代替吗？第一步可以使用>4卡吗

**Comment by zkcys001** [comment]
1和3其实是一个问题吧，这个代码因为BN统计量的原因用4卡才能达到文中的精度。
reid这个问题对BN很敏感，因为涉及到PK采样的问题，如果你想用2卡的话你可以考虑把batchsize除以2，lr也除以2试一下，不能保证精度。建议使用默认的4卡设置。

Direct infer指的是source训练好之后直接在target测试。

**Comment by Youngboy12** [comment]
好的，非常感谢！

**Comment by Youngboy12** [comment]
好的，非常感谢！还是第二个问题，这里的“source训练”是指Stronger Baseline训练 还是 Uncertainty训练？

**Comment by zkcys001** [comment]
source训练应该就是正常的有标注的训练，report的结果是Stronger Baseline那的‘’sh scripts/pretrain_market1501.sh‘’代码跑出来的结果，就是去掉REA数据增强的有监督reid的训练方式。

**Comment by Youngboy12** [comment]
非常感谢！还有一个问题，我在做Uncertainty第二步的训练（dbscan_uncertainty_duke2market.sh）时，在第6个epoch之前一直是正常的，但是第6个epoch重新聚类后，mAP开始下降，到第9个epoch预测结果为Nan。跑了三遍都是这样，源代码没有修改。请问您知道是什么原因吗

**Comment by zkcys001** [comment]
2卡训练我一直没有调过，4卡没这个问题。
