### ISSUE TITLE
训练到一定epoch之后（50+）模型输出、loss会变成nan 

### ISSUE THREAD

**Issue by yanty123** [zkcys001/UDAStrongBaseline#25]
uncertainty 这份代码，不知道您有没有遇到过这种情况。

祝好！

**Comment by zkcys001** [comment]
好像在之前遇到过，这份代码没有，你可以加我微信聊哈，微信号：zkcloudly

**Comment by YuSuen** [comment]
我也遇到了，但性能最好的都是在50 epoch以内，之后性能不会再比之前高甚至是下降，过拟合了？所以是不是可以直接把epoch改为50？ @zkcys001
