### ISSUE TITLE
missing sbs_traindbscan_unc.py

### ISSUE THREAD

**Issue by yjh576** [zkcys001/UDAStrongBaseline#6]
Sorry, I haven't found sbs_traindbscan_unc.py mentioned in dbscan_uncertainty_duke2market.sh. Could you share with me?

**Comment by zkcys001** [comment]
Thank you for your interest! Since we have some deadlines recently, we do not have enough time to sort out the code. And I have updated an unsorted code. 
I'll update with a cleaner version of the code when I'm ready
Thanks for your understanding.
