### ISSUE TITLE
The result of GLT much lower than paper's

### ISSUE THREAD

**Issue by woocoder** [zkcys001/UDAStrongBaseline#8]
Hi, I follow the readme to run the GLT code.
![image](https://user-images.githubusercontent.com/11451001/116814639-84664c80-ab8c-11eb-88d6-99bfdd04a4a0.png)
And the result mAP is 57.3% in duke->market task (10 iteration), which much lower than paper's 79.5%.
![image](https://user-images.githubusercontent.com/11451001/116814722-e0c96c00-ab8c-11eb-8e33-f0ae84fc0984.png)
![image](https://user-images.githubusercontent.com/11451001/116814762-f9d21d00-ab8c-11eb-88f1-54020d68df66.png)
How can I do to improve the result like paper's? 
Thanks for your attention.

**Comment by zkcys001** [comment]
Thanks for your attentionThe result you showed is to use single time kmeans clustering.  You can use kmean clustering many times to improve performance.  In fact，the dbscan can achieve higher performance.  I suggest you try to use the stronger baseline or uncertainty model~-------- 原始邮件 --------发件人： woocoder ***@***.***>日期： 2021年5月2日周日 晚上9:27收件人： zkcys001/UDAStrongBaseline ***@***.***>抄送： Subscribed ***@***.***>主    题： [zkcys001/UDAStrongBaseline] The result of GLT much lower than paper's (#8)
Hi, I follow the readme to run the GLT code.

And the result mAP is 57.3% in duke->market task (10 iteration), which much lower than paper's 79.5%.


How can I do to improve the result like papers?
Thanks for your attention.

**Comment by zkcys001** [comment]
Thanks for your attention. The result you showed is to use single-time K-means clustering.  You can use K-means clustering many times to improve performance.  I reproduced the GLT code last several weeks, but it seems to still have some latent bugs, and I will update it recently.

In fact, the DBSCAN can achieve higher performance.  I suggest you try to use the stronger baseline or uncertainty model, which are based on DBSCAN~It takes less times than the K-means

In addition, you must use the 4 gpus to train the model.

**Comment by woocoder** [comment]
Thank you for your reply. I will try it later. 
Very nice job!
Looking forward to the upcoming updates~
